fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    archive: "https://github.com/voxpupuli/puppet-archive.git"
    augeas_core: "https://github.com/puppetlabs/puppetlabs-augeas_core.git"
  symlinks:
    bamboo: "#{source_dir}"
